movie_pjt_version1/MOVIE_PJT/movie_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

movie_pjt_version1/MOVIE_PJT/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('<int:movie_id>', views.movie_detail, name='movie_detail'),
    path('<int:movie_id>/edit/', views.movie_update, name='movie_update'),
    path('<int:movie_id>/delete/', views.movie_delete, name='movie_delete'),

    path('<int:movie_id>/scores/new/', views.score_create, name='score_create'),
    path('<int:movie_id>/scores/<int:score_id>/delete/', views.score_delete, name='score_delete'),
    path('search/', views.search_movie, name='search_movie'),
]

movie_pjt_version1/MOVIE_PJT/movies/models.py
from django.db import models
from accounts.models import User
# Create your models here.

#
# class Genre(models.Model):
#     name = models.CharField(max_length=20)
#
#     def __str__(self):
#         return f'{self.id}: {self.name}'
#
#
# class Nation(models.Model):
#     name = models.CharField(max_length=20)
#
#     def __str__(self):
#         return f'{self.id}: {self.name}'
#
#
# class Grade(models.Model):
#     name = models.CharField(max_length=20)
#
#     def __str__(self):
#         return f'{self.id}: {self.name}'

# 영화코드, 영화명(국문), 영화명(영문), 상영시간, 상영국가, 영화장르,
# 감독1명, 배우3명, 영화상영등급, 누적관객수, 개봉일, 이미지url, 줄거리, 예고편url
class Movie(models.Model):
    movie_cd = models.CharField(max_length=20, blank=True, null=True)
    title_ko = models.CharField(max_length=100, blank=True, null=True)
    title_en = models.CharField(max_length=100, blank=True, null=True)
    movie_tm = models.CharField(max_length=50, blank=True, null=True)
    nation = models.CharField(max_length=50, blank=True, null=True)
    genre = models.CharField(max_length=50, blank=True, null=True)
    director = models.CharField(max_length=100, blank=True, null=True)
    actor1 = models.CharField(max_length=100, blank=True, null=True)
    actor2 = models.CharField(max_length=100, blank=True, null=True)
    actor3 = models.CharField(max_length=100, blank=True, null=True)
    grade = models.CharField(max_length=50, blank=True, null=True)
    audience = models.CharField(max_length=100, blank=True, null=True)
    open_dt = models.CharField(max_length=100, blank=True, null=True)
    poster_url = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    trailer_url = models.TextField(blank=True, null=True)
    score_sum = models.IntegerField(default=0)
    average_score = models.FloatField(default=0)

    class Meta:
        ordering=['-average_score']

    # def __str__(self):
    #     return f'{self.id}: {self.title_ko[:20]}'

class Score(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    value = models.IntegerField()


    class Meta:
        ordering=['-value']

    # def __str__(self):
    #     return f'{self.movie.title_ko}: {self.value}, {self.content[:30]}'

movie_pjt_version1/MOVIE_PJT/movies/forms.py
from django import forms
from .models import Score


class ScoreModelForm(forms.ModelForm):
    value = forms.IntegerField(min_value=0, max_value=10)

    class Meta:
        model = Score
        fields = [
            'value', 'content',
        ]

movie_pjt_version1/MOVIE_PJT/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.views.decorators.http import require_http_methods, require_POST, require_GET
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import JsonResponse
from .models import Movie, Score
from .forms import ScoreModelForm
from django.contrib import messages


@require_GET
def movie_list(request):
    allmovies = Movie.objects.all()
    boxoffice = Movie.objects.all()
    boxoffice = list(reversed(sorted(boxoffice, key=lambda boxoffice: int(boxoffice.audience))))
    boxoffice = boxoffice[:10]

    # return JsonResponse({})
    return render(request, 'movies/movie_list.html', {
        'allmovies': allmovies,
        'boxoffice': boxoffice,
    })


@require_GET
def search_movie(request):

    keyword = request.GET.get('q')
    movies = Movie.objects.filter(title_ko__icontains=keyword)

    if keyword == '':
        movies = Movie.objects.all()

    if movies:
        res = serializers.serialize('json', movies)
        return JsonResponse(res, safe=False)
    else:
        movies = Movie.objects.filter(title_en__icontains=keyword)
        if movies:
            res = serializers.serialize('json', movies)
            return JsonResponse(res, safe=False)
        else:
            for i in range(3):
                if i == 0:
                    movies = Movie.objects.filter(actor1=keyword)
                    if movies:
                        res = serializers.serialize('json', movies)
                        return JsonResponse(res, safe=False)
                elif i == 1:
                    movies = Movie.objects.filter(actor2=keyword)
                    if movies:
                        res = serializers.serialize('json', movies)
                        return JsonResponse(res, safe=False)
                elif i == 2:
                    movies = Movie.objects.filter(actor3=keyword)
                    if movies:
                        res = serializers.serialize('json', movies)
                        return JsonResponse(res, safe=False)
            else:
                movies = Movie.objects.filter(genre=keyword)
                if movies:
                    res = serializers.serialize('json', movies)
                    return JsonResponse(res, safe=False)
                else:
                    movies = Movie.objects.filter(nation=keyword)
                    res = serializers.serialize('json', movies)
                    return JsonResponse(res, safe=False)




@require_http_methods(['GET'])
def movie_detail(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    movie.audience = format(int(movie.audience), ',')
    scores = movie.score_set.all()
    return render(request, 'movies/movie_detail.html' ,{
        'movie': movie,
        'movie.audience': movie.audience,
        'scores': scores,
    })

@require_http_methods(['GET', 'POST'])
def movie_update(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    if request.method == 'POST':
        movie.title = request.POST.get('title')
        movie.genre.name = request.POST.get('genre')
        movie.audience = request.POST.get('audience')
        movie.poster_url = request.POST.get('poster_url')
        movie.description = request.POST.get('description')
        movie.save()
        return redirect('movies:movie_detail', movie_id=movie.id)
    else:
        return render(request, 'movies/movie_edit.html', {
            'movie' : movie
        })

@require_http_methods(['POST'])
def movie_delete(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    movie.delete()
    return redirect('movies:movie_list')

@login_required
@require_POST
def score_create(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    form = ScoreModelForm(request.POST)
    if form.is_valid() == False:
        messages.add_message(request, messages.INFO, '점수와 내용 모두 입력해주세요 😊')
        return redirect('movies:movie_detail', movie.id)
    if form.is_valid():
        score = form.save(commit=False)
        score.movie = movie
        if len(score.content) < 10:
            messages.add_message(request, messages.INFO, '10글자 이상 작성해주세요.😊')
            return redirect('movies:movie_detail', movie.id)
        score.user = request.user
        user_score = Score.objects.all()
        for i in user_score:
            if request.user.id == i.user_id and score.movie.id == i.movie_id:
                messages.add_message(request, messages.INFO, '리뷰가 이미 있습니다.😉')
                # messages.add_message(request, '리뷰가 이미 있습니다.')
                return redirect('movies:movie_detail', movie.id)
        else:
            score.save()
            movie.score_sum += score.value
            movie.average_score = round(movie.score_sum / movie.score_set.count(), 1)
            movie.save()
    return redirect('movies:movie_detail', movie.id)


@require_POST
@login_required
def score_delete(request, movie_id, score_id):
    movie = get_object_or_404(Movie, id=movie_id)
    score = get_object_or_404(Score, id=score_id)
    if request.user == score.user:
        movie.score_sum -= score.value
        score.delete()
        if movie.score_set.all():
            movie.average_score = round(movie.score_sum / movie.score_set.count(), 1)
        else:
            movie.average_score = 0
        movie.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

movie_pjt_version1/MOVIE_PJT/movies/templates/movies/movie_edit.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'movies:movie_update' movie.id %}" method="POST">
        {% csrf_token %}
        <div class="div text-left my-4">
            <div class="mb-4">
                <h1>🎥 영화 상세정보 수정 페이지 🎥</h1>
            </div>
            <div class="mb-3 font-weight-bold">
                <label for="title">영화제목</label>
                <input type="text" class="form-control" name="title" id="title" value="{{ movie.title }}"
                       placeholder="한글로 작성해주세요"/>
            </div>
            <div class="mb-3 font-weight-bold">
                <label for="title_en">영화 장르 </label>
                <input type="text" class="form-control" name="genre" id="genre" value="{{ movie.genre.name }}"
                       placeholder="영어로 작성해주세요"/>
            </div>
            <div class="mb-3 font-weight-bold">
                <label for="audience">누적 관객수</label>
                <input type="number" class="form-control" name="audience" id="audience" value="{{ movie.audience }}"/>
            </div>
            <div class="mb-3 font-weight-bold">
                <label for="poster_url">영화 포스터 url</label>
                <input type="poster_url" class="form-control" name="poster_url" id="poster_url"
                       value="{{ movie.poster_url }}"/>
            </div>
            <div class="mb-3 font-weight-bold">
                <label for="description">영화 줄거리</label>
                <textarea name="description" class="form-control" id="description">{{ movie.description }}</textarea>
            </div>
            <div>
                <input class="btn btn-dark" type="submit" value="Submit"/>
            </div>
        </div>
    </form>
{% endblock %}

movie_pjt_version1/MOVIE_PJT/movies/templates/movies/movie_list.html
<style>
    .header_img {
        filter: brightness(60%);
    }

    .header_audience {
        font-weight: bold;
        font-size: 32px;
    }

    .header_title {
        font-weight: bold;
        font-size: 25px;
    }
</style>

{% extends 'base.html' %}

{% block body %}
    {% load static %}
    <div id="app">
        {#  boxoffice top10  #}

        <header id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <a :href="get_url(42)"><img src="{% static 'movies/1_극한직업.png' %}" class="d-block w-100 header_img"
                                                alt="1_극한직업"></a>
                    <div class="carousel-caption d-none d-md-block">
                        <p class="header_audience mb-2">누적관객수 1위</p>
                        <a :href="get_url(42)" style="color:white; text-decoration: none;"><p class="header_title mb-1">
                            극한직업</p></a>
                        <p>지금까지 이런 맛은 없었다 이것은 갈비인가, 통닭인가</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <a :href="get_url(1)"><img src="{% static 'movies/2_어벤져스.png' %}" class="d-block w-100 header_img"
                                               alt="2_어벤져스"></a>
                    <div class="carousel-caption d-none d-md-block">
                        <p class="header_audience mb-2">누적관객수 2위</p>
                        <a :href="get_url(1)" style="color:white; text-decoration: none;"><p class="header_title mb-1">
                            어벤져스: 엔드게임</p></a>
                        <p>인피니티 워 이후 절반만 살아남은 지구, 마지막 희망이 된 어벤져스</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <a :href="get_url(12)"><img src="{% static 'movies/3_캡틴마블.png' %}" class="d-block w-100 header_img"
                                                alt="3_캡틴마블"></a>
                    <div class="carousel-caption d-none d-md-block">
                        <p class="header_audience mb-2">누적관객수 3위</p>
                        <a :href="get_url(42)" style="color:white; text-decoration: none;"><p class="header_title mb-1">
                            캡틴 마블</p></a>
                        <p>위기에 빠진 어벤져스의 희망!</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <a :href="get_url(19)"><img src="{% static 'movies/4_돈.png' %}" class="d-block w-100 header_img"
                                                alt="4_돈"></a>
                    <div class="carousel-caption d-none d-md-block">
                        <p class="header_audience mb-2">누적관객수 4위</p>
                        <a :href="get_url(19)" style="color:white; text-decoration: none;"><p class="header_title mb-1">
                            돈</p></a>
                        <p>“부자가 되고 싶었다”</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <a :href="get_url(43)"><img src="{% static 'movies/5_증인.png' %}" class="d-block w-100 header_img"
                                                alt="5_증인"></a>
                    <div class="carousel-caption d-none d-md-block">
                        <p class="header_audience mb-2">누적관객수 5위</p>
                        <a :href="get_url(43)" style="color:white; text-decoration: none;"><p class="header_title mb-1">
                            증인</p></a>
                        <p>마음을 여는 순간, 진실이 눈앞에 다가왔다</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <a :href="get_url(44)"><img src="{% static 'movies/6_사바하.png' %}" class="d-block w-100 header_img"
                                                alt="6_사바하"></a>
                    <div class="carousel-caption d-none d-md-block">
                        <p class="header_audience mb-2">누적관객수 6위</p>
                        <a :href="get_url(44)" style="color:white; text-decoration: none;"><p class="header_title mb-1">
                            사바하</p></a>
                        <p>3사람들은 말했다. 그때, 그냥, 그것이 죽었어야 한다고…</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <a :href="get_url(52)"><img src="{% static 'movies/7_알리타.png' %}" class="d-block w-100 header_img"
                                                alt="7_알리타"></a>
                    <div class="carousel-caption d-none d-md-block">
                        <p class="header_audience mb-2">누적관객수 7위</p>
                        <a :href="get_url(52)" style="color:white; text-decoration: none;"><p class="header_title mb-1">
                            알리타: 배틀엔젤</p></a>
                        <p>인간의 두뇌를 가진 기계 소녀, 그녀는 인간인가? 기계인가? 진짜 나를 깨워라!</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <a :href="get_url(51)"><img src="{% static 'movies/8_드래곤길들이기.png' %}"
                                                class="d-block w-100 header_img" alt="8_드래곤길들이기"></a>
                    <div class="carousel-caption d-none d-md-block">
                        <p class="header_audience mb-2">누적관객수 8위</p>
                        <a :href="get_url(51)" style="color:white; text-decoration: none;"><p class="header_title mb-1">
                            드래곤 길들이기3</p></a>
                        <p>영원히 기억될 그들의 마지막 모험이 시작된다!</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <a :href="get_url(25)"><img src="{% static 'movies/9_어스.png' %}" class="d-block w-100 header_img"
                                                alt="9_어스"></a>
                    <div class="carousel-caption d-none d-md-block">
                        <p class="header_audience mb-2">누적관객수 9위</p>
                        <a :href="get_url(25)" style="color:white; text-decoration: none;"><p class="header_title mb-1">
                            어스</p></a>
                        <p>우리는 누구인가?</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <a :href="get_url(2)"><img src="{% static 'movies/10_나의특별한형제.png' %}"
                                               class="d-block w-100 header_img" alt="10_나의특별한형제"></a>
                    <div class="carousel-caption d-none d-md-block">
                        <p class="header_audience mb-2">누적관객수 10위</p>
                        <a :href="get_url(2)" style="color:white; text-decoration: none;"><p class="header_title mb-1">
                            나의 특별한 형제</p></a>
                        <p>머리 좀 쓰는 형 x 몸 좀 쓰는 동생! 세상엔 이런 형제도 있다!</p>
                    </div>
                </div>

            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </header>

        {#  서치바      #}
        <nav class="navbar navbar-dark flex-md-nowrap container my-3">
            <span class="navbar-brand"></span>
            <input class="form-control form-control-dark w-100 mr-3" type="text" placeholder="영화, 배우, 장르, 국가를 검색해보세요"
                   aria-label="Search"
                   v-model="search">
        </nav>

        {#        <p class="my-4 text-left month_movie">박스오피스</p>#}
        {#        <div class="row width mx-auto">#}
        {#            {% for top10movie in boxoffice %}#}
        {#                {{ top10movie.title_ko }}#}
        {#                {{ top10movie.audience }}#}
        {#                <br>#}
        {#            {% endfor %}#}
        {#        </div>#}

        <div id="app" class="container">
            <p class="my-4 text-left month_movie">🎞️ Box office </p>
            <div class="row mx-auto">
                <div v-if="movies" v-for="movie in movies" class="col-3 mb-2">
                    <a :href="get_url(movie.pk)" class="d-block font-weight-bold"><img class="img-size" :src="movie.fields.poster_url" alt="영화포스터"></a>
                    <div class="row">
                        <div class="col-8 text-truncate">
                            <a :href="get_url(movie.pk)" class="my-2 d-inline-block font-weight-bold" style="color: white;">${ movie.fields.title_ko }</a>
                        </div>
                        <div class="col-4 d-inline-block my-2"><i class="fas fa-star" style="color: red; font-size: 15px;"></i><span style="color: red;"> ${ movie.fields.average_score }</span></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}