movie_pjt_version1/MOVIE_PJT/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    path('', views.user_list, name='user_list'),
    path('<str:username>/', views.user_detail, name='user_detail'),
    path('follow/<str:username>/', views.toggle_follow, name='toggle_follow'),
]

movie_pjt_version1/MOVIE_PJT/movie_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

movie_pjt_version1/MOVIE_PJT/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('<int:movie_id>', views.movie_detail, name='movie_detail'),
    path('<int:movie_id>/edit/', views.movie_update, name='movie_update'),
    path('<int:movie_id>/delete/', views.movie_delete, name='movie_delete'),

    path('<int:movie_id>/scores/new/', views.score_create, name='score_create'),
    path('<int:movie_id>/scores/<int:score_id>/delete/', views.score_delete, name='score_delete'),
    path('search/', views.search_movie, name='search_movie'),
]

movie_pjt_version1/MOVIE_PJT/accounts/models.py
"""
0. User 모델 확장 가능성을 염두하라.
1. $ django-admin startproject MY_PROJECT
2. $ django-admin startapp accounts
3. accounts/models.py => 아래 코드 작성
4. settings.py => INSTALLED APPS += 'accounts'
5. settings.py => AUTH USERMODEL = 'accounts.User'
"""

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings', blank=True)

    def __str__(self):
        return self.username

movie_pjt_version1/MOVIE_PJT/movies/models.py
from django.db import models
from accounts.models import User
# Create your models here.

#
# class Genre(models.Model):
#     name = models.CharField(max_length=20)
#
#     def __str__(self):
#         return f'{self.id}: {self.name}'
#
#
# class Nation(models.Model):
#     name = models.CharField(max_length=20)
#
#     def __str__(self):
#         return f'{self.id}: {self.name}'
#
#
# class Grade(models.Model):
#     name = models.CharField(max_length=20)
#
#     def __str__(self):
#         return f'{self.id}: {self.name}'

# 영화코드, 영화명(국문), 영화명(영문), 상영시간, 상영국가, 영화장르,
# 감독1명, 배우3명, 영화상영등급, 누적관객수, 개봉일, 이미지url, 줄거리, 예고편url
class Movie(models.Model):
    movie_cd = models.CharField(max_length=20, blank=True, null=True)
    title_ko = models.CharField(max_length=100, blank=True, null=True)
    title_en = models.CharField(max_length=100, blank=True, null=True)
    movie_tm = models.CharField(max_length=50, blank=True, null=True)
    nation = models.CharField(max_length=50, blank=True, null=True)
    genre = models.CharField(max_length=50, blank=True, null=True)
    director = models.CharField(max_length=100, blank=True, null=True)
    actor1 = models.CharField(max_length=100, blank=True, null=True)
    actor2 = models.CharField(max_length=100, blank=True, null=True)
    actor3 = models.CharField(max_length=100, blank=True, null=True)
    grade = models.CharField(max_length=50, blank=True, null=True)
    audience = models.CharField(max_length=100, blank=True, null=True)
    open_dt = models.CharField(max_length=100, blank=True, null=True)
    poster_url = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    trailer_url = models.TextField(blank=True, null=True)
    score_sum = models.IntegerField(default=0)
    average_score = models.FloatField(default=0)

    class Meta:
        ordering=['-average_score']

    # def __str__(self):
    #     return f'{self.id}: {self.title_ko[:20]}'

class Score(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    value = models.IntegerField()


    class Meta:
        ordering=['-value']

    # def __str__(self):
    #     return f'{self.movie.title_ko}: {self.value}, {self.content[:30]}'

movie_pjt_version1/MOVIE_PJT/accounts/forms.py
from django import forms
from .models import User
# from django.contrib.auth import get_user_model 은 옆이랑 같은 말이다

from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm

class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

class UserCustomAuthenticationForm(AuthenticationForm):

    class Meta(AuthenticationForm):
        model = User

movie_pjt_version1/MOVIE_PJT/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from .forms import UserCustomAuthenticationForm, UserCustomCreationForm
from .models import User

# Create your views here.
@require_http_methods(["GET", "POST"])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:movie_list')
    if request.method == 'POST':
        user_form = UserCustomCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            auth_login(request, user)
            return redirect('movies:movie_list')
    else:
        user_form = UserCustomCreationForm()
    context = {'form': user_form}
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:movie_list')
    if request.method == 'POST':
        login_form = UserCustomAuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            print(request.META.get('HTTP_REFERER'))
            return redirect('movies:movie_list')
    else:
        login_form = UserCustomAuthenticationForm()
    context = {'form': login_form}
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:movie_list')


def user_list(request):
    users = User.objects.all()
    return render(request, 'accounts/user_list.html', {
        'users': users
    })

def user_detail(request, username):
   user_info = User.objects.get(username=username)
   return render(request, 'accounts/user_detail.html', {
       'user_info': user_info,
   })

@login_required
@require_POST
def toggle_follow(request, username):
    sender = request.user
    receiver = get_object_or_404(User, username=username)

    if sender != receiver:
        if receiver in sender.followers.all():
            # unfollow
            sender.followers.remove(receiver)
        else:
            # follow
            sender.followers.add(receiver)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER','/movies/'))

movie_pjt_version1/MOVIE_PJT/accounts/templates/accounts/login.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic+Coding:400,700&amp;subset=korean" rel="stylesheet">
    <title>Document</title>
     <style>
        body {
            background: black;
            color: white;
            font-family: 'Noto Sans', sans-serif;
        }
     </style>
</head>
{% load bootstrap4 %}
{% load static %}
<body>
    <nav class="row text-center sticky-top" style="background-color: rgba(0,0,0,0.7)">
        <div class="col">

        </div>
        <div class="col">
            <a href="{% url 'movies:movie_list' %}"><img src="{% static 'movies/netflix.png' %}" style="width:200px;" alt="넷플릭스"></a>
        </div>
        <div class="col">

        </div>
</nav>
    <div class="my-5 mx-auto" style="width: 400px">
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-danger">로그인</button>
                <a class="d-inline-block ml-2" href="{% url 'accounts:signup' %}"><button type="button" class="btn btn-danger">회원가입</button></a>
            {% endbuttons %}

        </form>


    </div>
</body>
</html>

movie_pjt_version1/MOVIE_PJT/accounts/templates/accounts/signup.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic+Coding:400,700&amp;subset=korean" rel="stylesheet">
    <title>Document</title>
     <style>
        body {
            background: black;
            color: white;
            font-family: 'Noto Sans', sans-serif;
        }
     </style>
</head>
{% load bootstrap4 %}
{% load static %}
<body>
    <nav class="row text-center sticky-top" style="background-color: rgba(0,0,0,0.7)">
        <div class="col">

        </div>
        <div class="col">
            <a href="{% url 'movies:movie_list' %}"><img src="{% static 'movies/netflix.png' %}" style="width:200px;"></a>
        </div>
        <div class="col">

        </div>
</nav>
    <div class="my-5 mx-auto" style="width: 500px">
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-danger">회원가입</button>
            {% endbuttons %}
        </form>
    </div>
</body>
</html>

movie_pjt_version1/MOVIE_PJT/accounts/templates/accounts/user_detail.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-8">
                <div class="row">
                    {% if user == user_info %}
                        <p class="mt-5" style="font-family: 'Noto Sans', sans-serif; font-size: 30px; font-weight: 700;">안녕하세요, {{user.username}} 님!</p>
                    {% endif %}
                    {% if user != user_info %}
                        {% if user_info.is_staff == False %}
                            <p class="mt-5" style="font-family: 'Noto Sans', sans-serif; font-size: 30px; font-weight: 700;">{{user_info.username}} 님의 페이지입니다</p>
                        {% elif user_info.is_staff == True %}
                            <p class="mt-5" style="font-family: 'Noto Sans', sans-serif; font-size: 30px; font-weight: 700;">👑Master 님의 페이지입니다</p>
                        {% endif %}

                    {% endif %}

                        {% if user != user_info %}
                            <form class="mt-5 ml-3" action="{% url 'accounts:toggle_follow' user_info.username %}" method="POST">
                            {% csrf_token %}
                                {% if user_info in user.followers.all %}
                                    <button type="submit" class="btn btn-danger px-1 py-1 mt-1">언팔로우하기</button>
                                {% else %}
                                    <button type="submit" class="btn btn-success px-1 py-1 mt-1">팔로우하기</button>
                                {% endif %}
                            </form>

                        {% endif %}
                </div>

                <div class="row ml-4">
                    <!-- 팔로우 Modal button -->
                    <p data-toggle="modal" data-target="#followModal" style="border-bottom: 1px solid white; cursor: pointer; font-family: 'Noto Sans', sans-serif; font-size: 20px"><i class="far fa-grin-beam"></i> 팔로우 {{ user_info.followers.all.count }}</p>


                    <!-- 팔로우 Modal -->
                    <div class="modal fade" id="followModal" tabindex="-1" role="dialog"
                         aria-labelledby="followModalLabel" aria-hidden="true" style="color:black; ">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <p class="modal-title" id="followModalLabel"
                                       style="font-size: 20px; font-family: 'Noto Sans', sans-serif; font-weight: 700;">
                                        팔로잉</p>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    {% if user_info.followers.all %}

                                    {% for user in user_info.followers.all %}
                                    <div class="ml-3 my-2"><a href="{% url 'accounts:user_detail' user.username %}">💛 {{ user.username }}</a></div>
                                    {% endfor %}

                                    {% endif %}
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- 팔로워 Modal button -->
                    <p class="ml-4" data-toggle="modal" data-target="#followerModal" style="border-bottom: 1px solid white; cursor: pointer; font-family: 'Noto Sans', sans-serif; font-size: 20px"><i class="far fa-smile-wink"></i> 팔로워 {{ user_info.followings.all.count }}</p>


                    <!-- 팔로워 Modal -->
                    <div class="modal fade" id="followerModal" tabindex="-1" role="dialog"
                         aria-labelledby="followerModalLabel" aria-hidden="true" style="color:black; ">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <p class="modal-title" id="followerModalLabel"
                                       style="font-size: 20px; font-family: 'Noto Sans', sans-serif; font-weight: 700;">
                                        팔로워</p>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    {% if user_info.followings.all %}
                                        {% for user in user_info.followings.all %}
                                        <div class="ml-3"><a href="{% url 'accounts:user_detail' user.username %}">💜 {{ user.username }}</a></div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="my-4" style="font-family: 'Noto Sans', sans-serif;">
            {% if user == user_info %}
                <p class="mb-3" style="font-size: 24px; font-weight: bold;">⭐{{user.username}} 님을 위한 영화 추천⭐</p>
                <div class="row ml-3">
                {% for friend in  user_info.followers.all %}
                    {% if friend.score_set.first %}
                    <div class="col-3">
                        <a href="{% url 'movies:movie_detail' friend.score_set.first.movie.id %}" style="color: white; font-weight: bold;" class="mb-2"><p style="font-size: 16.5px;">🎬 {{ friend.score_set.first.movie.title_ko }}</p></a>
                        <img class="d-block" src="{{ friend.score_set.first.movie.poster_url }}" alt="{{ friend.score_set.first.movie.title_ko }}" style="width:100%;">
                    </div>
                    {% else %}
                    {% endif %}
                {% endfor %}
                </div>

            {% endif %}
        </div>

        <div class="mb-3 mt-5" style="font-family: 'Noto Sans', sans-serif;">
            {% if user == user_info %}
                <div class="mb-4" >
                <p style="font-size: 24px; font-weight: bold;">📝 내 리뷰 보기</p>
                <hr  align="left" style="border: solid 1px white; width: 60%;">
                </div>
            {% endif %}
            {% if user != user_info %}
                {% if user_info.is_staff == False %}
                    <div class="mb-4" >
                    <p style="font-size: 24px; font-weight: bold;">📝 {{user_info.username}}님의 리뷰 보기</p>
                    <hr  align="left" style="border: solid 1px white; width: 60%;">
                    </div>
                {% elif user_info.is_staff == True %}
                    <div class="mb-4" >
                    <p style="font-size: 24px; font-weight: bold;">📝 Master님의 리뷰 보기</p>
                    <hr  align="left" style="border: solid 1px white; width: 60%;">
                    </div>
                {% endif %}
            {% endif %}

            {% if user_info.score_set.all %}
                    {% for score in user_info.score_set.all %}
                        <div class="ml-4 my-4">
                            <a href="{% url 'movies:movie_detail' score.movie.id %}" style="color: white; font-weight: bold; font-size: 20px;">{{ score.movie.title_ko }}</a><i class="fas fa-star ml-2" style="color: red; font-size: 15px;"><span class="ml-2">{{ score.value }}.0</span></i>
                            <p class="ml-4 mt-3" style="color: white;"> ◻️ {{ score.content }}</p>
{#                            <hr  align="left" style="border: solid 1px white; width: 60%;">#}
                        </div>
                    {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock %}

movie_pjt_version1/MOVIE_PJT/accounts/templates/accounts/user_list.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
    <p class="mt-5" style="font-family: 'Noto Sans', sans-serif; font-size: 30px; font-weight: 700;">다양한 친구를 만나보세요.</p>
            {% for user in users %}
                {% if user != request.user%}
                    <div class="mx-5 my-2" style="font-family: 'Noto Sans', sans-serif; font-size: 20px;">
                        <a href="{% url 'accounts:user_detail' user.username %}" style="color: white">✔ {{ user.username }} 님의 페이지 가기</a>
                    </div>
                {% endif %}
            {% endfor %}
    </div>

{% endblock %}