movie_pjt_version1/MOVIE_PJT/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    path('', views.user_list, name='user_list'),
    path('<str:username>/', views.user_detail, name='user_detail'),
    path('follow/<str:username>/', views.toggle_follow, name='toggle_follow'),
]

movie_pjt_version1/MOVIE_PJT/movie_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

movie_pjt_version1/MOVIE_PJT/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('<int:movie_id>', views.movie_detail, name='movie_detail'),
    path('<int:movie_id>/edit/', views.movie_update, name='movie_update'),
    path('<int:movie_id>/delete/', views.movie_delete, name='movie_delete'),

    path('<int:movie_id>/scores/new/', views.score_create, name='score_create'),
    path('<int:movie_id>/scores/<int:score_id>/delete/', views.score_delete, name='score_delete'),
    path('search/', views.search_movie, name='search_movie'),
]

movie_pjt_version1/MOVIE_PJT/movie_pjt/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>🎥NOTFLIX</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic+Coding:400,700&amp;subset=korean" rel="stylesheet">
     <style>
        body {
            background: black;
            color: white;
            font-family: 'Noto Sans', sans-serif;
            overflow-x: hidden;
        }

        .month_movie {
            font-family: 'Noto Sans', sans-serif;
            font-weight: 700;
            font-size: 30px;
        ;
        }

        .img-size {
            width: 100%;
        }

        .posthead {
            font-family: 'Noto Sans';
            font-weight: 700;
            color: gray;
        }

        .base_button {
            margin-top: 35px;
            margin-right: 100px;
        }

        .movie_score {
            font-size: 20px;
        }
    </style>
</head>
<body>
    {% load static %}

    <nav class="row text-center sticky-top" style="background-color: rgba(0,0,0,0.7)">
            <div class="col">

            </div>
            <div class="col">
                <a href="{% url 'movies:movie_list' %}"><img src="{% static 'movies/netflix.png' %}" style="width:200px;"></a>
            </div>
            <div class="col">
                 {% if user.is_authenticated %}
                    <div class="base_button">
                        <a class="d-inline-block" href="{% url 'accounts:user_list'%}"><button type="button" class="btn btn-danger">😃 사용자 리스트</button></a>
                        <a class="d-inline-block" href="{% url 'accounts:user_detail' user.username %}"><button type="button" class="btn btn-danger">마이페이지</button></a>
                        <a class="d-inline-block" href="{% url 'accounts:logout' %}"><button type="button" class="btn btn-danger">로그아웃</button></a>
                    </div>

                {% else %}
                    <div class="base_button">
                        <a class="d-inline-block" href="{% url 'accounts:login' %}"><button type="button" class="btn btn-danger">로그인</button></a>
                        <a class="d-inline-block" href="{% url 'accounts:signup' %}"><button type="button" class="btn btn-danger">회원가입</button></a>
                    </div>
                {% endif %}
            </div>
    </nav>

    <div>
        {% block body %}
        {% endblock %}
    </div>
    <div class="text-white text-center my-5">
        <a href="#" class="text-white ">
            <i class="fas fa-arrow-circle-up fa-2x"></i>
        </a>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/axios.js' %}"></script>
    <script src="{% static 'js/vue.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>